# Generated by Django 5.1.5 on 2025-01-18 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0003_recomendacao_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacao',
            old_name='key',
            new_name='usuario',
        ),
    ]
