# Generated by Django 5.1.5 on 2025-01-18 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0004_rename_key_recomendacao_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomendacao',
            options={'verbose_name': 'Recomendações'},
        ),
    ]
