# Generated by Django 5.1.5 on 2025-01-18 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0005_alter_recomendacao_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacao',
            old_name='titulo',
            new_name='tituslo',
        ),
    ]
