# Generated by Django 5.1.5 on 2025-01-18 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0006_rename_titulo_recomendacao_tituslo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recomendacao',
            old_name='tituslo',
            new_name='titulo',
        ),
    ]
