# Generated by Django 5.1.5 on 2025-01-20 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0007_rename_tituslo_recomendacao_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomendacao',
            name='usuario',
        ),
    ]
