# Generated by Django 5.1.5 on 2025-01-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0009_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfi'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='idade',
            field=models.CharField(max_length=11),
        ),
    ]
