# Generated by Django 5.1.5 on 2025-01-20 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0010_alter_perfil_options_alter_perfil_idade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recomendacao',
            options={'verbose_name': 'Recomendaçõe'},
        ),
    ]
