# Generated by Django 5.1.5 on 2025-01-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0011_alter_recomendacao_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendacao',
            name='perfil',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recomendacao.perfil'),
        ),
    ]
