# Generated by Django 5.1.5 on 2025-01-20 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0014_rename_idade_perfil_data_nascimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='data_nascimento',
            new_name='data_de_nascimento',
        ),
    ]
