# Generated by Django 5.1.5 on 2025-01-22 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0015_rename_data_nascimento_perfil_data_de_nascimento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='cpf',
        ),
    ]
