# Generated by Django 5.1.5 on 2025-01-27 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0016_remove_perfil_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='data_de_nascimento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
