# Generated by Django 5.1.5 on 2025-01-27 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0017_alter_perfil_data_de_nascimento_alter_perfil_genero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='descricao',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='link',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
    ]
