# Generated by Django 5.1.5 on 2025-01-27 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recomendacao', '0018_alter_recomendacao_descricao_alter_recomendacao_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendacao',
            name='link',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='recomendacao',
            name='titulo',
            field=models.CharField(max_length=300),
        ),
    ]
